Modification in release-service-to-artifacts 5

diff --git a/.github/workflows/release-service-to-artifacts.yml b/.github/workflows/release-service-to-artifacts.yml
--- a/.github/workflows/release-service-to-artifacts.yml
+++ b/.github/workflows/release-service-to-artifacts.yml
@@ -136,12 +136,12 @@ jobs:
       # Step 13: Generate or Update index.json
       - name: Update index.json with new versions
         run: |
-
           released_artifact="tunnel-integration.zip"
+
           # Verify the artifact exists
           if [ ! -f "$released_artifact" ]; then
-          echo "Error: Released artifact $released_artifact not found."
-          exit 1
+            echo "Error: Released artifact $released_artifact not found."
+            exit 1
           fi
 
           echo "Using released artifact: $released_artifact"
@@ -162,13 +162,9 @@ jobs:
           index_name="tuf-repo/updates-not-released-index/${basename}-index.json"
           echo "Index file: $index_name"
 
-          echo "Checking for existing index.json..."
-          if [ -f "$index_name" ]; then
-          echo "$index_name exists, loading it."
-          else
-          echo "$index_name does not exist, creating a new one."
+          # Overwrite or create a new index.json file with an empty JSON object
+          echo "Resetting $index_name to an empty JSON object..."
           echo '{}' > "$index_name"
-          fi
 
           # Access the version output from the previous step
           version="${{ steps.pushing-GAR.outputs.version }}"
@@ -177,13 +173,13 @@ jobs:
 
           # Update the JSON index file
           jq --arg file "$filename" \
-          --arg length "$length" \
-          --arg sha256 "$sha256" \
-          --arg version "$version" \
-          '.[$file] = {length: ($length | tonumber), hashes: {sha256: $sha256}, version: $version}' "$index_name" > tmp.json && mv tmp.json "$index_name"
+            --arg length "$length" \
+            --arg sha256 "$sha256" \
+            --arg version "$version" \
+            '.[$file] = {length: ($length | tonumber), hashes: {sha256: $sha256}, version: $version}' "$index_name" > tmp.json && mv tmp.json "$index_name"
 
           echo "Updated $index_name"
-          cat "$index_name" 
+          cat "$index_name"
 
       # Step 14: Commit and Push index.json to the Target Repository
       - name: Commit and Push index.json
