Modifications to the release to clients workflow

diff --git a/.github/workflows/release-to-clients.yml b/.github/workflows/release-to-clients.yml
--- a/.github/workflows/release-to-clients.yml
+++ b/.github/workflows/release-to-clients.yml
@@ -12,7 +12,69 @@ jobs:
       id-token: write
 
     steps:
-      # Step 1: Clone the Target Repository
+
+      # Step 1: Authenticate with Google Cloud
+      - name: Authenticate with Google Cloud
+        uses: google-github-actions/auth@v2
+        with: 
+          token_format: access_token
+          workload_identity_provider: projects/185640679849/locations/global/workloadIdentityPools/github/providers/github-prov
+          service_account: github-actions-auth@polished-medium-445107-i9.iam.gserviceaccount.com
+          access_token_lifetime: '600s'
+
+      # Step 2: Reading the version of the last uploaded release to Google Artifact Registry
+      - name: Reading the last uploaded release to Google Artifact Registry
+        run: |
+          service_name=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)
+          echo "Getting the last released version to Google Artifact Registry"
+          VERSION=$(gcloud artifacts versions list \
+            --location=europe-southwest1 \
+            --project=polished-medium-445107-i9 \
+            --repository=nebula-storage \
+            --package=$service_name \
+            --sort-by=~createTime \
+            --limit=1 \
+            --format="value(VERSION)")
+          echo "Latest version is $VERSION"
+          echo "VERSION=$VERSION" >> $GITHUB_ENV
+      
+      # Step 3: Reading the files that are inside the latest uploaded version
+      - name: Reading the files that are inside this uploaded last version
+        run: |
+          echo "Listing files in version $VERSION"
+          FILES=$(gcloud artifacts files list \
+            --location=europe-southwest1 \
+            --project=polished-medium-445107-i9 \
+            --repository=nebula-storage \
+            --package=$service_name \
+            --version=$VERSION \
+            --format="value(name)")
+          echo "Files in the version:"
+          echo "$FILES"
+          echo "FILES=$FILES" >> $GITHUB_ENV
+
+      # Step 4: Computing the size of the listed files
+      - name: Compute File Sizes in Latest Version
+        id: compute_sizes
+        run: |
+          echo "Listing files and their sizes in version $VERSION"
+          FILE_SIZES=$(gcloud artifacts files list \
+            --location=europe-southwest1 \
+            --project=polished-medium-445107-i9 \
+            --repository=nebula-storage \
+            --package=$service_name \
+            --version=$VERSION \
+            --format="csv[no-heading](name,sizeBytes)")
+          
+          echo "Files and sizes:"
+          echo "$FILE_SIZES"
+
+          # Compute total size
+          TOTAL_SIZE=$(echo "$FILE_SIZES" | awk -F',' '{sum += $2} END {print sum}')
+          echo "Total size of files: $TOTAL_SIZE bytes"
+          echo "TOTAL_SIZE=$TOTAL_SIZE" >> $GITHUB_ENV
+
+      # Step 4: Clone the Target Repository
       - name: Clone Target Repository
         env:
           TUF_REPO_URL: ${{ secrets.TUF_REPO_URL }}
@@ -22,6 +84,60 @@ jobs:
           cd tuf-repo
           git config user.name "github-actions[bot]"
           git config user.email "github-actions[bot]@users.noreply.github.com"
+
+
+      # Step 4: Generate or Update index.json
+      - name: Generate the new service's index.json
+        run: |
+        
+          service_name=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)
+          
+          # Verify the artifact exists
+          if [ ! -f "$released_artifact" ]; then
+            echo "Error: Released artifact $released_artifact not found."
+            exit 1
+          fi
+
+          echo "Using released artifact: $released_artifact"
+
+          # Compute the length and sha256 of the released artifact
+          length=$(stat -c%s "$released_artifact")
+          sha256=$(sha256sum "$released_artifact" | awk '{print $1}')
+
+          echo "Artifact Length: $length"
+          echo "Artifact SHA256: $sha256"
+
+          # Extract the filename from the artifact
+          filename=$released_artifact
+          echo "The filename is: $filename"
+
+          # Correct the index.json file path
+          basename="${filename%.zip}"
+          index_name="tuf-repo/updates-not-released-index/${basename}-index.json"
+          echo "Index file: $index_name"
+
+          # Overwrite or create a new index.json file with an empty JSON object
+          echo "Resetting $index_name to an empty JSON object..."
+          echo '{}' > "$index_name"
+
+          # Access the version output from the previous step
+          version="${{ env.tag }}"
+
+          # Path in which the .zip is stored in the Google Artifact Registry
+          path="https://artifactregistry.googleapis.com/download/v1/projects/polished-medium-445107-i9/locations/europe-southwest1/repositories/nebula-storage/files/${service_name}:${version}:${zip_name}:download?alt=media"
+
+          echo "File: $filename, Length: $length, SHA256: $sha256, Version: $version"
+
+          # Update the JSON index file
+          jq --arg file "$basename" \
+            --arg length "$length" \
+            --arg sha256 "$sha256" \
+            --arg version "$version" \
+            --arg path "$path" \
+            '.[$file] = {length: ($length | tonumber), path: $path, hashes: {sha256: $sha256}, version: $version}' "$index_name" > tmp.json && mv tmp.json "$index_name"
+
+          echo "Updated $index_name"
+          cat "$index_name"
 
       # Step 2: List all the -index.json files in updates-not-released
       # In this file is indicated which has been the last release to Google 
